# Generated by Django 6.1.1 on 2026-09-17 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0025_service_unique_per_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(default=dict, verbose_name='分析结果')),
                ('analyzed_at', models.DateTimeField(auto_now=True, verbose_name='分析时间')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='分析耗时(毫秒)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internet_analyses', to='assets.device', verbose_name='GSLB 设备')),
            ],
            options={
                'verbose_name': '互联网资产分析缓存',
                'verbose_name_plural': '互联网资产分析缓存',
                'ordering': ('-analyzed_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('device',), name='uni_internet_analysis_device')],
            },
        ),
    ]
