[project]
name = "network-ops"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.1",
    "django-filter>=26.1",
    "djangorestframework>=3.18.0",
    "gitpython>=3.1.61",
    "openpyxl>=3.1.5",
    "psycopg2-binary>=2.9.12",
    "ttp>=0.10.1",
]

[tool.pyright]
include = ["apps"]
exclude = ["**/node_modules","**/.*", "**/__pycache__", ".venv", ".git"]
reportIncompatibleVariableOverride = false

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W"]
ignore = ["F405", "F403", "E402"]

[tool.ruff.lint.isort]
known-first-party = ["assets", "core", "ops"]

[tool.ruff.lint.per-file-ignores]
"**/migrations/*" = ["E501"]

[dependency-groups]
dev = [
    "django-extensions>=4.1",
    "django-stubs>=6.1.0",
    "djangorestframework-stubs>=3.18.1",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]
