"""Django settings 基础层：**所有「可被环境变量影响」的配置在这里只定义一遍**。

设计原则（分层依据）：
    - 环境变量本身就是环境区分机制——同一个 `os.environ.get` / `_env_list` 写一遍，
      靠各环境注入不同的值即可，**不需要每个环境文件重写一遍读取逻辑**；
    - 环境文件只放**不走环境变量、但必须按环境硬改**的东西（守卫、写死值）：
        dev.py       空（base 即 dev 语义）
        container.py 两条 host 必填守卫（防 env/app.env 被误删一行）
        prod.py      DEBUG=False 硬覆盖 + 5 个关键 env 必填守卫（fail loud）
    - 分发与覆盖顺序见 __init__.py（DJANGO_ENV 白名单）。

凭据链路统一：`*_FILE > 同名环境变量 > 默认值`（_env_or_file）。`*_FILE` secrets
机制**只在容器里使用**（env/app.env 指向 /run/secrets/*）；宿主直跑按 .env.example
指南只 export 环境变量，不设 *_FILE 即走中间层。

硬规矩（防循环导入）：本文件与三个环境文件只允许 `from .base import ...`、标准库与
Django 的 import；**禁止** `from netops.settings import ...` / `from . import ...`——
反向依赖父包的执行结果会在 `__init__` 半初始化时炸（ModuleNotFoundError /
ImportError: cannot import name；BASE_DIR 那次事故就是这个形态）。

Generated by 'django-admin startproject' using Django 6.1.
更多背景：https://docs.djangoproject.com/en/6.1/topics/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).parent.parent.parent.resolve()


def _env_list(name: str, default: str = "") -> list[str]:
    """逗号分隔的环境变量 → 列表（去空白、丢空项）；未设置时用 default。"""
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


def _env_or_file(name: str, default: str = "") -> str:
    """读一个配置值：`<NAME>_FILE` 指向的文件优先（Docker secrets），其次环境变量，最后默认值。

    Docker secrets 在 compose（非 swarm）下就是把密钥挂成 `/run/secrets/<name>` 文件；
    postgres 官方镜像认 `POSTGRES_PASSWORD_FILE` 这套 `*_FILE` 变量，Django 侧得自己读。
    优先顺序与「谁更该赢」一致：显式给的密钥文件 > 进程环境 > 内置默认值。

    文件存在但读不出来时**直接报错**，不静默回退到默认密码——那只会把「密钥配错了」
    伪装成「数据库连不上」。内容 strip() 与 postgres 官方 entrypoint 的 `$(cat file)`
    行为一致（去掉结尾换行），否则末尾换行会变成密码的一部分。

    使用约定：*_FILE secrets 只在容器里设置（env/app.env）；宿主直跑不设 *_FILE，
    自然走同名环境变量层——链路三个环境统一，不分叉。
    """
    path = os.environ.get(f"{name}_FILE")
    if path:
        try:
            return Path(path).read_text(encoding="utf-8").strip()
        except OSError as exc:
            raise ImproperlyConfigured(f"{name}_FILE={path} 读取失败：{exc}") from exc
    return os.environ.get(name, default)


# ---------------------------------------------------------------------------
# 环境动态配置（env 动态 + 各环境可接受的默认值；dev 的语义即此段的默认行为）
# ---------------------------------------------------------------------------

# 密钥：允许经 DJANGO_SECRET_KEY 注入生产级密钥；未设置沿用开发期密钥（拆分前行为）。
# prod.py 另有守卫：生产必须注入（它查 os.environ 原始值，不吃这里的 fallback）。
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or "django-insecure-bua49zfleexo##5iy2q^dm@880a5kdvh5q6%1zss&p#xe1y13$"

# DEBUG：默认开（开发/当前容器行为一致），DJANGO_DEBUG=0 收紧。
# prod.py 会硬覆盖为 False——生产的 DEBUG 不吃环境变量后门。
DEBUG = os.environ.get("DJANGO_DEBUG", "1").lower() in ("1", "true", "yes")

# 允许的 Host：默认放开（无域名阶段），上线用 DJANGO_ALLOWED_HOSTS 收紧为具体域名/IP。
# nginx 用 `proxy_set_header Host $http_host` 透传原样 Host（含端口），Django 必须放行；
# 校验时 Django 会剥掉端口再比对（localhost:8000 匹配 localhost）。prod.py 有必填守卫。
ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", "*")

# CSRF 可信来源（Django 4+ 的 Origin 校验）：正常拓扑留空即可——nginx 透传原样 Host，
# Origin 天然等于「当前 host」。需要显式声明的只有「浏览器看到的来源 ≠ 转发给 Django 的
# Host」的拓扑（外层 LB 改写 Host、TLS 提前终结等）；值必须带 scheme，逗号分隔，例如：
#   DJANGO_CSRF_TRUSTED_ORIGINS='https://netops.example.com,http://localhost:8000'
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

# Database —— env 动态；默认值是宿主 localhost 语义（dev 无 env 即此值）。
# 容器由 env/app.env 注入 HOST=db 与 *_FILE=/run/secrets/*；prod.py 守卫要求 HOST 必填。
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "netops"),
        "USER": _env_or_file("POSTGRES_USER", "netops"),
        "PASSWORD": _env_or_file("POSTGRES_PASSWORD", "netops_password"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": int(os.environ.get("POSTGRES_PORT", "5432")),
    }
}

# Redis / Celery 连接 —— env 动态；默认宿主 localhost。容器注入 REDIS_HOST=redis；
# prod.py 守卫要求 REDIS_HOST 必填。redis 官方镜像没有 *_FILE 机制，密码只走环境变量。
REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT = int(os.environ.get("REDIS_PORT", 6379))
REDIS_DB = int(os.environ.get("REDIS_DB", 0))
REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD", "")

if REDIS_PASSWORD:
    REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
else:
    REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# 访问流（AccessFlow）重建链路的旋钮与任务名约定：
# - 背压阈值：生产者投递前查 Stream 积压，超过就 self.retry 让路（不占 worker 进程）；
# - 投递开关：测试里默认关（conftest 统一置 False），否则 PolicySaver 每保存一次
#   就往真实 Redis 发消息；
# - 任务名唯一定义处：ingest 的投递触点（access_flow_trigger）按它 send_task——不 import
#   analysis（依赖方向单向）；analysis.tasks 的 name= 与下方 CELERY_TASK_ROUTES 的 key
#   必须与之一致，tests/analysis/test_access_flow_task.py 有对账断言。
ACCESS_FLOW_MAX_QUEUE = int(os.environ.get("ACCESS_FLOW_MAX_QUEUE", "50000"))
ACCESS_FLOW_DISPATCH = os.environ.get("ACCESS_FLOW_DISPATCH", "1").lower() in ("1", "true", "yes")
ACCESS_FLOW_TASK = "analysis.rebuild_access_flows"


# ---------------------------------------------------------------------------
# 以下为环境无关的静态配置
# ---------------------------------------------------------------------------

# 反向代理：信任 nginx 传递的原始协议
#
# nginx 已配置 `proxy_set_header X-Forwarded-Proto $scheme`，但 nginx → Django
# 之间走的是 HTTP，Django 默认会认为请求并非 HTTPS。声明信任该头之后，
# request.is_secure() 才能正确反映客户端侧的协议；否则启用 HTTPS 后会出现
# 重定向循环、Secure Cookie 不下发、CSRF Origin 校验失败等问题。
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    # GinIndex（analysis.AccessFlow 的 device_ids / policy_ids）要求这个 app 在册
    "django.contrib.postgres",
    "core.apps.CoreConfig",
    "ingest.apps.OperatorConfig",
    "assets.apps.AssetsConfig",
    "analysis.apps.AnalysisConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "netops.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "netops.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
FRONTEND = BASE_DIR / "frontend" / "dist"
STATIC_ROOT = BASE_DIR / "www"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
AUTH_USER_MODEL = "core.User"

# DRF
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # 列表接口统一启用搜索与排序，各 ViewSet 通过 search_fields / ordering_fields 声明可用字段
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # 列表接口统一数字分页：默认每页 50 条，客户端可用 ?page_size= 覆盖（上限 500）
    "DEFAULT_PAGINATION_CLASS": "netops.pagination.StandardPagination",
    "PAGE_SIZE": 50,
}

# Celery 行为（与环境无关；broker / result backend 的连接串见上方 Redis 段）
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = ["json"] if False else "json"
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 3600
CELERY_TASK_SOFT_TIME_LIMIT = 3000
# 访问流重建走独立队列：队列仍独立（积压可观测、将来可随时拆出独占 worker），
# 当前由 docker-compose 的 worker 一并消费（-Q celery,access_flow，两条链皆低频）
CELERY_TASK_ROUTES = {
    # 键 = ACCESS_FLOW_TASK（2026-09 随域拆分由 ingest.rebuild_access_flows 迁来；
    # 任务名变更 → Redis 里未消费的旧消息会 Unknown task，升级前停 worker 清队列）
    "analysis.rebuild_access_flows": {"queue": "access_flow"},
}
