# Generated by Django 6.0.1 on 2026-01-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='device',
            name='connect_failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='连接失败时间'),
        ),
    ]
