# Generated by Django 6.0.1 on 2026-01-14 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_remove_device_created_at_remove_device_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(verbose_name='配置内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='保存时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='cmdb.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备配置',
                'verbose_name_plural': '设备配置',
                'ordering': ['-time'],
            },
        ),
    ]
