# Generated by Django 6.0.1 on 2026-01-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_deviceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='parsed_config',
            field=models.JSONField(blank=True, null=True, verbose_name='解析后的配置信息'),
        ),
    ]
