# Generated by Django 6.0.1 on 2026-01-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_device_parsed_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='parsed_config',
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='parsed_config',
            field=models.JSONField(blank=True, null=True, verbose_name='解析后的配置信息'),
        ),
    ]
