# Generated by Django 6.0.1 on 2026-01-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_remove_device_parsed_config_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceconfig',
            old_name='config',
            new_name='config_text',
        ),
        migrations.RemoveField(
            model_name='deviceconfig',
            name='parsed_config',
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='config_json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON格式的配置内容'),
        ),
    ]
