# Generated by Django 6.0.1 on 2026-01-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_rename_config_deviceconfig_config_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='interface_json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON格式的接口配置内容'),
        ),
    ]
