# Generated by Django 6.0.1 on 2026-01-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_deviceconfig_interface_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='node_json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON格式的ltm Node配置内容'),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='pool_json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON格式的ltm Pool配置内容'),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='virtual_json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON格式的ltm VS配置内容'),
        ),
    ]
