# Generated by Django 6.0.1 on 2026-01-29 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_deviceconfig_node_json_deviceconfig_pool_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('raw', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Persist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('raw', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('monitors', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PoolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('raw', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SNAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vs_address', models.CharField(max_length=255)),
                ('vs_port', models.CharField(max_length=15, null=True)),
                ('snat_type', models.CharField(max_length=255, null=True)),
                ('pool', models.CharField(max_length=255, null=True)),
                ('snat_pool', models.CharField(max_length=255, null=True)),
                ('profiles', models.JSONField(default=list)),
                ('rules', models.JSONField(default=list)),
                ('persist', models.JSONField(default=list)),
            ],
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['hostname'], name='idx_hostname'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['address'], name='idx_address'),
        ),
        migrations.AddIndex(
            model_name='deviceconfig',
            index=models.Index(fields=['device', '-time'], name='idx_config_latest'),
        ),
        migrations.AddField(
            model_name='irule',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irules', to='cmdb.deviceconfig'),
        ),
        migrations.AddField(
            model_name='persist',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persist', to='cmdb.deviceconfig'),
        ),
        migrations.AddField(
            model_name='pool',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='cmdb.deviceconfig'),
        ),
        migrations.AddField(
            model_name='poolmember',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cmdb.pool'),
        ),
        migrations.AddField(
            model_name='profile',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='cmdb.deviceconfig'),
        ),
        migrations.AddField(
            model_name='snat',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snatpool', to='cmdb.deviceconfig'),
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_servers', to='cmdb.deviceconfig'),
        ),
        migrations.AddIndex(
            model_name='pool',
            index=models.Index(fields=['config', 'name'], name='idx_pool_config'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(fields=('config', 'name'), name='uni_pool_config'),
        ),
        migrations.AddIndex(
            model_name='poolmember',
            index=models.Index(fields=['name'], name='idx_member_name'),
        ),
        migrations.AddIndex(
            model_name='virtualserver',
            index=models.Index(fields=['name'], name='idx_vs_name'),
        ),
        migrations.AddIndex(
            model_name='virtualserver',
            index=models.Index(fields=['pool'], name='idx_pool_name'),
        ),
        migrations.AddIndex(
            model_name='virtualserver',
            index=models.Index(fields=['config'], name='idx_config'),
        ),
        migrations.AddConstraint(
            model_name='virtualserver',
            constraint=models.UniqueConstraint(fields=('config', 'name'), name='uni_vs_config'),
        ),
    ]
