# Generated by Django 6.0.1 on 2026-01-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_irule_persist_pool_poolmember_profile_snat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irule',
            options={'verbose_name': 'LTM IRule', 'verbose_name_plural': 'LTM IRule'},
        ),
        migrations.AlterModelOptions(
            name='persist',
            options={'verbose_name': 'LTM Persist', 'verbose_name_plural': 'LTM Persist'},
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'verbose_name': 'LTM Pool', 'verbose_name_plural': 'LTM Pool'},
        ),
        migrations.AlterModelOptions(
            name='poolmember',
            options={'verbose_name': 'LTM PoolMbr', 'verbose_name_plural': 'LTM PoolMbr'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'LTM Profile', 'verbose_name_plural': 'LTM Profile'},
        ),
        migrations.AlterModelOptions(
            name='snat',
            options={'verbose_name': 'LTM SNAT', 'verbose_name_plural': 'LTM SNAT'},
        ),
        migrations.AlterModelOptions(
            name='virtualserver',
            options={'verbose_name': 'LTM Virtual', 'verbose_name_plural': 'LTM Virtual'},
        ),
        migrations.AddIndex(
            model_name='irule',
            index=models.Index(fields=['name'], name='idx_rule_name'),
        ),
        migrations.AddIndex(
            model_name='persist',
            index=models.Index(fields=['name'], name='idx_persist_name'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['name'], name='idx_profile_name'),
        ),
        migrations.AddIndex(
            model_name='snat',
            index=models.Index(fields=['name'], name='idx_snatpool_name'),
        ),
    ]
