# Generated by Django 6.0.1 on 2026-01-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_alter_irule_options_alter_persist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualserver',
            name='mask',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='protocol',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='source',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
