# Generated by Django 6.0.1 on 2026-01-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_virtualserver_mask_virtualserver_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualserver',
            name='persist',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
