# Generated by Django 6.0.1 on 2026-02-20 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0012_alter_virtualserver_persist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('shutdown', models.BooleanField(default=False)),
                ('vrf', models.CharField(max_length=255, null=True)),
                ('mode', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('access_vlan', models.CharField(max_length=255, null=True)),
                ('combo_type', models.CharField(max_length=255, null=True)),
                ('ip_address', models.CharField(max_length=255, null=True)),
                ('subnet_mask', models.CharField(max_length=255, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='cmdb.deviceconfig')),
            ],
        ),
    ]
