# Generated by Django 6.0.1 on 2026-02-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_interface'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VirtualServer',
            new_name='LtmVirtualServer',
        ),
    ]
