# Generated by Django 6.0.1 on 2026-02-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_rename_virtualserver_ltmvirtualserver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pool',
            new_name='LtmPool',
        ),
    ]
