# Generated by Django 6.0.1 on 2026-02-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_rename_pool_ltmpool'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IRule',
            new_name='LtmIRule',
        ),
        migrations.RenameModel(
            old_name='Persist',
            new_name='LtmPersist',
        ),
        migrations.RenameModel(
            old_name='PoolMember',
            new_name='LtmPoolMember',
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='LtmProfile',
        ),
        migrations.RenameModel(
            old_name='SNAT',
            new_name='LtmSNAT',
        ),
    ]
