# Generated by Django 6.0.1 on 2026-02-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_rename_irule_ltmirule_rename_persist_ltmpersist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GtmDatacenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datacenters', to='cmdb.deviceconfig')),
            ],
        ),
        migrations.CreateModel(
            name='GtmPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lb_mode', models.CharField(default='round-robin', max_length=255)),
                ('alternate_mode', models.CharField(default='round-robin', max_length=255)),
                ('fallback_mode', models.CharField(default='return-to-dns', max_length=255)),
                ('fallback_ip', models.GenericIPAddressField(null=True)),
                ('ttl', models.IntegerField(default=30)),
                ('members', models.JSONField(default=list)),
                ('monitor', models.JSONField(default=list)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gtmpools', to='cmdb.deviceconfig')),
            ],
        ),
        migrations.CreateModel(
            name='GtmWideip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lb_mode', models.CharField(max_length=255)),
                ('pools', models.JSONField(default=list, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wideips', to='cmdb.deviceconfig')),
            ],
        ),
    ]
