# Generated by Django 6.0.1 on 2026-02-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_gtmdatacenter_gtmpool_gtmwideip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gtmwideip',
            options={'verbose_name': 'GTM Wideip', 'verbose_name_plural': 'GTM Wideip'},
        ),
        migrations.AddIndex(
            model_name='gtmwideip',
            index=models.Index(fields=['name'], name='idx_wideip_name'),
        ),
        migrations.AddIndex(
            model_name='gtmwideip',
            index=models.Index(fields=['config'], name='idx_wideip_config'),
        ),
        migrations.AddConstraint(
            model_name='gtmwideip',
            constraint=models.UniqueConstraint(fields=('config', 'name'), name='uni_wideip_config'),
        ),
    ]
