# Generated by Django 6.0.1 on 2026-02-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0018_alter_gtmwideip_options_gtmwideip_idx_wideip_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconfig',
            name='interface_json',
        ),
        migrations.RemoveField(
            model_name='deviceconfig',
            name='node_json',
        ),
        migrations.RemoveField(
            model_name='deviceconfig',
            name='pool_json',
        ),
        migrations.RemoveField(
            model_name='deviceconfig',
            name='virtual_json',
        ),
    ]
