# Generated by Django 6.0.1 on 2026-02-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0020_rename_shutdown_interface_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='latest',
            field=models.BooleanField(default=True),
        ),
    ]
