# Generated by Django 6.0.1 on 2026-02-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0021_deviceconfig_latest'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deviceconfig',
            name='idx_config_latest',
        ),
        migrations.AddIndex(
            model_name='deviceconfig',
            index=models.Index(fields=['device', 'latest'], name='idx_config_latest'),
        ),
    ]
