# Generated by Django 6.0.1 on 2026-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0022_remove_deviceconfig_idx_config_latest_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deviceconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('latest', True)), fields=('device',), name='uni_latest_config_per_device'),
        ),
    ]
