# Generated by Django 6.1 on 2026-09-01 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_tag_subnet_ipaddress'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Celery任务ID')),
                ('task_type', models.CharField(choices=[('collect_config', '采集配置'), ('backup_config', '备份配置'), ('ansible_playbook', 'Ansible执行'), ('batch_collect', '批量采集'), ('config_backup', '配置备份')], max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('params', models.JSONField(default=dict, verbose_name='任务参数')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='任务结果')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='assets.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('collection', '数据采集'), ('parsing', '配置解析'), ('storage', '数据存储')], max_length=50, verbose_name='阶段类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('input_data', models.JSONField(default=dict, verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, null=True, verbose_name='输出数据')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='最大重试次数')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '阶段',
                'verbose_name_plural': '阶段',
                'ordering': ('created_at',),
            },
        ),
    ]
