# Generated by Django 6.1 on 2026-09-07 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_add_arpmac'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubnetUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ips', models.PositiveIntegerField(default=0, verbose_name='总 IP 数')),
                ('used_ips', models.PositiveIntegerField(default=0, verbose_name='已使用')),
                ('utilization', models.FloatField(default=0, verbose_name='使用率 (%)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='assets.subnet', verbose_name='网段')),
            ],
            options={
                'verbose_name': '子网使用率',
                'verbose_name_plural': '子网使用率',
                'ordering': ('-recorded_at',),
            },
        ),
    ]
