# Generated by Django 6.1 on 2026-09-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_add_subnet_usage_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='assets.device', verbose_name='所属设备'),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='vid',
            field=models.PositiveIntegerField(verbose_name='VLAN ID'),
        ),
        migrations.AddConstraint(
            model_name='vlan',
            constraint=models.UniqueConstraint(fields=('device', 'vid'), name='uni_vlan_device_vid'),
        ),
    ]
