# Generated by Django 6.1 on 2026-09-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_add_vlan_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={'ordering': ('device', 'name', '-pk'), 'verbose_name': '地址簿', 'verbose_name_plural': '地址簿'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('hostname',), 'verbose_name': '网络设备', 'verbose_name_plural': '网络设备'},
        ),
        migrations.AlterModelOptions(
            name='deviceaccount',
            options={'ordering': ('device', 'username', '-pk'), 'verbose_name': '设备账号', 'verbose_name_plural': '设备账号'},
        ),
        migrations.AlterModelOptions(
            name='deviceconnection',
            options={'ordering': ('-created_at', '-pk'), 'verbose_name': '设备连接信息', 'verbose_name_plural': '设备连接信息'},
        ),
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'ordering': ('name',), 'verbose_name': '设备型号', 'verbose_name_plural': '设备型号'},
        ),
        migrations.AlterModelOptions(
            name='gtmdatacenter',
            options={'ordering': ('device', 'name', '-pk'), 'verbose_name': 'GTM Datacenter', 'verbose_name_plural': 'GTM Datacenter'},
        ),
        migrations.AlterModelOptions(
            name='gtmpool',
            options={'ordering': ('device', 'name', '-pk'), 'verbose_name': 'GTM Pool', 'verbose_name_plural': 'GTM Pool'},
        ),
        migrations.AlterModelOptions(
            name='gtmwideip',
            options={'ordering': ('device', 'name'), 'verbose_name': 'GTM Wide IP', 'verbose_name_plural': 'GTM Wide IP'},
        ),
        migrations.AlterModelOptions(
            name='interface',
            options={'ordering': ('device', 'interface'), 'verbose_name': '网络接口', 'verbose_name_plural': '网络接口'},
        ),
        migrations.AlterModelOptions(
            name='ltmirule',
            options={'ordering': ('device', 'name', '-pk'), 'verbose_name': 'LTM iRule', 'verbose_name_plural': 'LTM iRule'},
        ),
        migrations.AlterModelOptions(
            name='ltmpersist',
            options={'ordering': ('device', 'name', '-pk'), 'verbose_name': 'LTM Persist', 'verbose_name_plural': 'LTM Persist'},
        ),
        migrations.AlterModelOptions(
            name='ltmpool',
            options={'ordering': ('device', 'name'), 'verbose_name': 'LTM Pool', 'verbose_name_plural': 'LTM Pool'},
        ),
        migrations.AlterModelOptions(
            name='ltmpoolmember',
            options={'ordering': ('pool_name', 'name', '-pk'), 'verbose_name': 'LTM Pool Member', 'verbose_name_plural': 'LTM Pool Member'},
        ),
        migrations.AlterModelOptions(
            name='ltmprofile',
            options={'ordering': ('device', 'name', '-pk'), 'verbose_name': 'LTM Profile', 'verbose_name_plural': 'LTM Profile'},
        ),
        migrations.AlterModelOptions(
            name='ltmsnat',
            options={'ordering': ('device', 'name', '-pk'), 'verbose_name': 'LTM SNAT', 'verbose_name_plural': 'LTM SNAT'},
        ),
        migrations.AlterModelOptions(
            name='ltmvirtualserver',
            options={'ordering': ('device', 'name'), 'verbose_name': 'LTM Virtual Server', 'verbose_name_plural': 'LTM Virtual Server'},
        ),
        migrations.AlterModelOptions(
            name='natrule',
            options={'ordering': ('device', 'order'), 'verbose_name': 'NAT 规则', 'verbose_name_plural': 'NAT 规则'},
        ),
        migrations.AlterModelOptions(
            name='ntpconfig',
            options={'ordering': ('-created_at', '-pk'), 'verbose_name': 'NTP配置', 'verbose_name_plural': 'NTP配置'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ('device', 'order'), 'verbose_name': '安全策略', 'verbose_name_plural': '安全策略'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('vrf', 'destination', 'nexthop', '-pk'), 'verbose_name': '路由', 'verbose_name_plural': '路由'},
        ),
        migrations.AlterModelOptions(
            name='securityzone',
            options={'ordering': ('name',), 'verbose_name': '安全区', 'verbose_name_plural': '安全区'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',), 'verbose_name': '服务', 'verbose_name_plural': '服务'},
        ),
        migrations.AlterModelOptions(
            name='snmpconfig',
            options={'ordering': ('-created_at', '-pk'), 'verbose_name': 'SNMP配置', 'verbose_name_plural': 'SNMP配置'},
        ),
        migrations.AlterModelOptions(
            name='syslogconfig',
            options={'ordering': ('-created_at', '-pk'), 'verbose_name': 'Syslog配置', 'verbose_name_plural': 'Syslog配置'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('name',), 'verbose_name': '设备厂商', 'verbose_name_plural': '设备厂商'},
        ),
        migrations.AlterModelOptions(
            name='vrf',
            options={'ordering': ('device', 'name'), 'verbose_name': 'VRF', 'verbose_name_plural': 'VRF'},
        ),
    ]
