# Generated by Django 6.1.1 on 2026-09-16 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_addressbook_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltmpoolmember',
            name='port',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='端口'),
        ),
        migrations.AddField(
            model_name='ltmvirtualserver',
            name='status',
            field=models.CharField(default='enabled', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='GtmServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='服务器名称')),
                ('datacenter', models.CharField(blank=True, default='', max_length=255, verbose_name='数据中心')),
                ('monitor', models.CharField(blank=True, default='', max_length=255, verbose_name='监控')),
                ('server_type', models.CharField(blank=True, default='', max_length=255, verbose_name='产品类型')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': 'GTM Server',
                'verbose_name_plural': 'GTM Server',
                'ordering': ('device', 'name', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='GtmVServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='虚拟服务器名称')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='地址')),
                ('port', models.CharField(blank=True, default='', max_length=15, verbose_name='端口')),
                ('monitor', models.CharField(blank=True, default='', max_length=255, verbose_name='监控')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.device', verbose_name='关联设备')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_servers', to='assets.gtmserver', verbose_name='所属服务器')),
            ],
            options={
                'verbose_name': 'GTM Virtual Server',
                'verbose_name_plural': 'GTM Virtual Server',
                'ordering': ('device', 'server', 'name', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='gtmserver',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='uni_gtmserver_device_name'),
        ),
        migrations.AddConstraint(
            model_name='gtmvserver',
            constraint=models.UniqueConstraint(fields=('device', 'server', 'name'), name='uni_gtmvserver_device_server_name'),
        ),
    ]
