# Generated by Django 6.1.1 on 2026-09-16 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_ltmpoolmember_port_ltmvirtualserver_status_gtmserver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='设备组名称')),
                ('group_type', models.CharField(choices=[('cluster', '集群'), ('ha', '主备'), ('failover', '故障接管'), ('stack', '堆叠'), ('single', '单机')], default='single', max_length=20, verbose_name='组类型')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设备组',
                'verbose_name_plural': '设备组',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DeviceGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_role', models.CharField(choices=[('master', '主'), ('backup', '备'), ('member', '成员')], default='member', max_length=20, verbose_name='设备角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='assets.device', verbose_name='设备')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='assets.devicegroup', verbose_name='设备组')),
            ],
            options={
                'verbose_name': '设备组成员',
                'verbose_name_plural': '设备组成员',
                'ordering': ('group', 'device', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('group', 'device'), name='uni_group_member')],
            },
        ),
    ]
