# Generated by Django 6.1.1 on 2026-09-16 04:01

from django.db import migrations, models


def forwards(apps, schema_editor):
    """历史数据：原 loadbalancer 统一改为 slb。

    原先 loadbalancer 同时承载 GSLB(GTM) 与 SLB(LTM) 两种解析器，无法自动区分，
    因此这里统一迁为 slb；确实提供 GSLB 的设备请人工改为 gslb。
    """
    Device = apps.get_model("assets", "Device")
    Device.objects.filter(device_type="loadbalancer").update(device_type="slb")


def backwards(apps, schema_editor):
    Device = apps.get_model("assets", "Device")
    Device.objects.filter(device_type__in=["slb", "gslb"]).update(device_type="loadbalancer")


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_devicegroup_devicegroupmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('firewall', '防火墙'), ('switch', '交换机'), ('slb', '服务器负载均衡'), ('gslb', '全局负载均衡'), ('router', '路由器'), ('server', '服务器'), ('dns', '域名解析'), ('dwdm', '波分复用'), ('internalac', '上网行为管理'), ('wirelessac', '无线控制器')], max_length=50, verbose_name='设备类型'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
