# Generated by Django 6.1.1 on 2026-09-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natrule',
            name='destination_addresses',
            field=models.ManyToManyField(blank=True, related_name='destination_nat_rules', to='assets.addressbook', verbose_name='匹配目的地址'),
        ),
        migrations.AlterField(
            model_name='natrule',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='nat_rules', to='assets.service', verbose_name='匹配服务'),
        ),
        migrations.AlterField(
            model_name='natrule',
            name='source_addresses',
            field=models.ManyToManyField(blank=True, related_name='source_nat_rules', to='assets.addressbook', verbose_name='匹配源地址'),
        ),
    ]
