# Generated by Django 6.1.1 on 2026-09-16 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_configbase_vlan_snmpconfig_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntpconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否生效'),
        ),
        migrations.AddField(
            model_name='syslogconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否生效'),
        ),
        migrations.AlterField(
            model_name='ntpconfig',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.device', verbose_name='关联设备'),
        ),
        migrations.AlterField(
            model_name='syslogconfig',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.device', verbose_name='关联设备'),
        ),
    ]
