# Generated by Django 6.1.1 on 2026-09-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_configbase_ntp_syslog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='service',
            name='uni_service_name',
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='uni_service_name'),
        ),
    ]
