# Generated by Django 6.1.1 on 2026-09-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_ltmpoolmember_configbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, default='', max_length=255, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP 地址')),
                ('owner', models.CharField(blank=True, default='', max_length=255, verbose_name='负责人')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务器负责人',
                'verbose_name_plural': '服务器负责人',
                'ordering': ('ip',),
            },
        ),
    ]
