# Generated by Django 6.1.1 on 2026-09-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0027_serverowner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="destination",
            field=models.CharField(max_length=45, verbose_name="目的网段 (CIDR)"),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="network",
            field=models.CharField(max_length=45, unique=True, verbose_name="网段 (CIDR)"),
        ),
    ]
