# Generated by Django 6.1.1 on 2026-09-22 10:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0001_internet_analysis_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField(verbose_name='源地址')),
                ('src_prefix', models.PositiveSmallIntegerField(verbose_name='源前缀长度')),
                ('src_range_end', models.CharField(blank=True, default='', max_length=45, verbose_name='源结束地址')),
                ('dst_ip', models.GenericIPAddressField(verbose_name='目的地址')),
                ('dst_prefix', models.PositiveSmallIntegerField(verbose_name='目的前缀长度')),
                ('dst_range_end', models.CharField(blank=True, default='', max_length=45, verbose_name='目的结束地址')),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('tcp-udp', 'TCP/UDP'), ('icmp', 'ICMP'), ('any', 'ANY')], max_length=10, verbose_name='协议')),
                ('port', models.CharField(blank=True, default='', max_length=15, verbose_name='起始端口')),
                ('port2', models.CharField(blank=True, default='', max_length=15, verbose_name='结束端口')),
                ('contexts', models.JSONField(default=dict, verbose_name='命中上下文')),
                ('device_ids', models.JSONField(default=list, verbose_name='设备ID列表')),
                ('policy_ids', models.JSONField(default=list, verbose_name='策略ID列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '访问流',
                'verbose_name_plural': '访问流',
                'ordering': ('-updated_at', '-pk'),
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['device_ids'], name='gin_accessflow_device_ids'), django.contrib.postgres.indexes.GinIndex(fields=['policy_ids'], name='gin_accessflow_policy_ids')],
                'constraints': [models.UniqueConstraint(fields=('src_ip', 'src_prefix', 'src_range_end', 'dst_ip', 'dst_prefix', 'dst_range_end', 'protocol', 'port', 'port2'), name='uni_accessflow_key')],
            },
        ),
    ]
